apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: msb-argo-app
resources:
  - ../../base
patches:
  - target:
      kind: Deployment
      name: msb-frontend
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 5
  - target:
      kind: Deployment
      name: msb-backend
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 3
labels:
  - includeSelectors: false
    pairs:
      site: dc
