apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: msb-argo-test
resources:
  - ../../base
patches:
  - target:
      kind: Deployment
      name: msb-argo-test
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 2
labels:
  - includeSelectors: false
    pairs:
      site: dc
